nav:
  - Home: index.md
  - Overview: overview
  - 新特性: whats-new
  - msProf: msprof
  - PyTorch Profiler: torch_npu_profiler
  - MSPTI: mspti
  - msMonitor: msmonitor
  - msprof-analyze: msprof-analyze
  - MindStudio Insight: msinsight
  - msAgent: msagent
  - Profiling Cases: profiling-cases
